apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efood-dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: admins-svc
                port:
                  number: 3000
            path: /api/v1/admins/?(.*)
            pathType: Prefix
          - backend:
              service:
                name: auth-svc
                port:
                  number: 3000
            path: /api/v1/auth/?(.*)
            pathType: Prefix
          
