apiVersion: skaffold/v2beta18
kind: Config
deploy:
  kubectl:
    manifests:
      - './k8s/services/*'
build:
  local:
    push: true
  artifacts:
    - image: efood/admins
      context: ../admins_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/auth
      context: ../auth_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/balances
      context: ../balances_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/catalogs
      context: ../catalogs_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/customers
      context: ../customers_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/deliveries
      context: ../deliveries_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/loyalties
      context: ../loyalties_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/merchants
      context: ../merchants_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/notifications
      context: ../notifications_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/orders
      context: ../orders_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/otp
      context: ../otp_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/payments
      context: ../payments_service
      docker:
        dockerfile: prod.Dockerfile
