apiVersion: skaffold/v2beta18
kind: Config
deploy:
  kubectl:
    manifests:
      - './k8s/services/*'
build:
  local:
    push: true
  artifacts:
    - image: efood/admins
      context: ../admins_service
      docker:
        dockerfile: prod.Dockerfile
    - image: efood/auth
      context: ../auth_service
      docker:
        dockerfile: prod.Dockerfile
