apiVersion: skaffold/v2beta18
kind: Config
deploy:
  kubectl:
    manifests:
      - './k8s/services/*'
      - './k8s/config/*'
build:
  local:
    push: false
  artifacts:
    - image: rekbers/auth
      context: ../auth_service
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: rekbers/admins
      context: ../admins_service
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
