apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orders-vs
spec:
  hosts:
    - orders-svc
  http:
  - match:
    - uri:
        prefix: /api/v1/orders
    route:
    - destination:
        host: orders-svc
        port:
          number: 3000
