apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payments-vs
spec:
  hosts:
    - payments-svc
  http:
  - match:
    - uri:
        prefix: /api/v1/payments
    route:
    - destination:
        host: payments-svc
        port:
          number: 3000
