apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: deliveries-vs
spec:
  hosts:
    - deliveries-svc
  http:
    - match:
        - uri:
            prefix: /api/v1/deliveries
      route:
        - destination:
            host: deliveries-svc
            port:
              number: 3000
