apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-vs
spec:
  hosts:
    - auth-svc
  http:
  - match:
    - uri:
        prefix: /api/v1/auth
    route:
    - destination:
        host: auth-svc
        port:
          number: 3000
