apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efood
      service: catalogs
  template:
    metadata:
      labels:
        app: efood
        service: catalogs
        sidecar.istio.io/inject: "true"
        version: "1"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: catalogs
        image: efood/catalogs
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - name: catalogs
            protocol: TCP
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: efood-config
