apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: otp-vs
spec:
  hosts:
    - otp-svc
  http:
  - match:
    - uri:
        prefix: /api/v1/otp
    route:
    - destination:
        host: otp-svc
        port:
          number: 3000
