apiVersion: v1
kind: Service
metadata:
  name: payments-svc
  labels:
    app: efood
    service: payments
spec:
  selector:
    app: efood
    service: payments
  ports:
    - name: http-port
      port: 3000
