version: '2'
services:
  admins:
    build:
      context: ../../admins_service
      dockerfile: dev.Dockerfile
    volumes:
      - ../../admins_service/src:/app/src
    env_file: ./.env
    depends_on:
      - dbpostgres
      - proxy
      - nats
      - redis
    expose:
      - '80'

  auth:
    build:
      context: ../../auth_service
      dockerfile: dev.Dockerfile
    volumes:
      - ../../auth_service/src:/app/src
    depends_on:
      - dbpostgres
      - proxy
      - nats
      - redis
    env_file: ./.env
    expose:
      - '80'

  proxy:
    build: ./
    ports:
      - 80:80
      - 443:443

  dbpostgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      - '6543:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nabati

  nats:
    image: nats
    command: "-js -sd /data -m 8222"
    volumes:
      - natsdata:/data:rw
    ports:
      - 4222:4222
      - 8222:8222

  redis:
    image: bitnami/redis:latest
    env_file: ./.env
    volumes:
      - redisdata:/bitnami/redis/data:rw
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
  natsdata:
    driver: local
  redisdata:
    driver: local
