apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: balances-vs
spec:
  hosts:
    - balances-svc
  http:
  - match:
    - uri:
        prefix: /api/v1/balances
    route:
    - destination:
        host: balances-svc
        port:
          number: 3000
